[features]
seeds = false
[programs.localnet]
sol_miner = "4Krw6BFxF5GN7ud6ui6Un8kdmL56wsL71BxtqxoAo9ro"

[programs.devnet]
sol_miner = "4Krw6BFxF5GN7ud6ui6Un8kdmL56wsL71BxtqxoAo9ro"

[programs.mainnet]
sol_miner = "4Krw6BFxF5GN7ud6ui6Un8kdmL56wsL71BxtqxoAo9ro"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/root/.config/solana/id-6ub.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
